### ISSUE TITLE
This nor Cue-SDK work on mac

### ISSUE THREAD

**Issue by mandray** [intrueder/cue-sdk-samples#6]
I already left a bug on cue-sdk, but I wanted to see if this worked for mac. This doesn't work on mac either

**Comment by intrueder** [comment]
Thanks for reporting this. I guess it does not work because requires cue-sdk. I will check this after adding macOS support for cue-sdk

**Comment by mandray** [comment]
That would be awesome. Thank you. If you need me to compile anything on my Mac please let me know I’ll help

**Comment by intrueder** [comment]
Oh! This should have been closed a long time ago as it works on macOS: https://github.com/CorsairOfficial/cue-sdk-node/issues/7
